version: "3"
services:
    ipfs:
        image: ipfs/go-ipfs
        working_dir: /data
        volumes: 
            - ./export:/export
            - ./data:/data/ipfs
            - ./www:/data/www
            - ./deploy.sh:/data/deploy.sh
        ports:
            - "${SWARM}:${SWARM}"
            - "${API}:${API}"
            - "${GATEWAY}:${GATEWAY}"
        command: ipfs config Addresses.API /ip4/0.0.0.0/tcp/${API} &
                    ipfs config Address.Gateway /ip4/0.0.0.0/tcp/${GATEWAY} &
                    ipfs config Address.Swarm /ip4/0.0.0.0/tcp/${SWARM} 